### ISSUE TITLE
Update the WP.org SVN repo

### ISSUE THREAD

**Issue by jrfnl** [fooplugins/debug-bar-screen-info#10]
Hiya, looks like the WP.org SVN repo is sorely out-of-date. If you like, add me as a contributor in SVN and I'll update it with the last two releases for you.

To add me as a contributor, visit https://wordpress.org/plugins/debug-bar-screen-info/admin/ and add 'jrf' under committers.

**Comment by bradvin** [comment]
cool - I have added you. Thanks for the help

**Comment by jrfnl** [comment]
No problem. Release done.
